### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by sami-0085** [sami-0085/gift_request#32]
### 実装予定の機能

- [ ] 新規登録
- [ ] ログイン
- [ ] プロフィール
- [ ] プロフィール編集
- [ ] パスワード変更
- [ ] リクエスト登録
- [ ] リクエスト詳細
- [ ] クエスト生成
- [ ] ユーザーのクエスト一覧
- [ ] みんなのクエスト一覧
- [ ] クエスト挑戦
- [ ] 答え合わせ

### 必要なページ
- [ ] トップページ
- [ ] トップページ（ログイン後）
- [ ] 新規登録ページ
- [ ] ログインページ
- [ ] マイページ、ユーザーのクエスト一覧ページ
- [ ] プロフィール編集ページ
- [ ] パスワードリセット申し込みページ
- [ ] パスワードリセットページ
- [ ] リクエスト作成ページ
- [ ] リクエスト、クエスト詳細ページ
- [ ] みんなのクエスト一覧ページ
- [ ] クエスト挑戦ページ
- [ ] 答え合わせページ
- [ ] 利用規約ページ
- [ ] プライバシーポリシーページ

**Comment by Tsuchiya2** [comment]
<img width="575" alt="スクリーンショット 2024-02-13 18 37 39" src="https://github.com/sami-0085/gift_request/assets/61481161/19127c5e-acb0-413f-b3ed-ec5afc4c3575">

Projectsにアクセスしましたが、看板・issue・ストーリーポイントが確認できませんでした。
カリキュラムの内容を確認して適切な形でご提出をお願いいたします。

**Comment by sami-0085** [comment]
鍵がかかっていたので、公開にしました。
ご確認の程よろしくお願いいたします。

**Comment by takyyk** [comment]
@sami-0085 
LGTMです！

**Comment by sami-0085** [comment]
ご確認ありがとうございます。
このまま進めさせていただきます！
